# Generated by Django 5.1.3 on 2024-11-17 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0002_alter_jogador_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartidaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perdedor1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perdedor1', to='controle.jogador')),
                ('perdedor2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perdedor2', to='controle.jogador')),
                ('vencedor1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vencedor1', to='controle.jogador')),
                ('vencedor2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vencedor2', to='controle.jogador')),
            ],
        ),
    ]
